version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/data/qdrant
  
  clearml:
    image: allegroai/clearml:latest
    environment:
      CLEARML_API_TOKEN: ${CLEARML_API_TOKEN}
      CLEARML_PROJECT_NAME: ${CLEARML_PROJECT_NAME}
      CLEARML_HOST_IP: ${CLEARML_HOST_IP}
    ports:
      - "8080:8080"
      - "8008:8008"
      - "8081:8081"
    volumes:
      - clearml_data:/opt/clearml/data
    depends_on:
      - mongodb

volumes:
  mongo_data:
  qdrant_data:
  clearml_data: